#!/bin/bash/python3

import os
import shutil

photos_dst = os.path.join(os.path.expanduser('~'), 'bestpix_data')

if os.path.exists(photos_dst):
    shutil.rmtree(photos_dst)

print()
print(f'Removing {photos_dst}')
print()