#!/bin/bash/python3

import os
import shutil

photos_dst = os.path.join(os.path.expanduser('~'), 'bestpix_data')

print(f'Removing folder: {photos_dst}')
if os.path.exists(photos_dst):
    shutil.rmtree(photos_dst)

print('Removing docker container named bestpix')
command_to_stop = '(docker stop bestpix || true && docker rm bestpix || true) 2>/dev/null'
os.system(command_to_stop)
