#!/bin/bash/python3

import os
import time
import shutil
import bestpix

os.system('clear')
time.sleep(1)

# copy the contencts of the host's "Photos Library.photoslibrary" to to mirrormirror_data 
photos_src = os.path.join(os.path.expanduser('~'), 'Pictures', 'Photos Library.photoslibrary')
photos_dst = os.path.join(os.path.expanduser('~'), 'bestpix_data')

print()
print(f'Making empty folder at: {photos_dst}')
print()

if os.path.exists(photos_dst):
    shutil.rmtree(photos_dst)

print('Copying folder contents:')
print(f'    from: {photos_src}')
print(f'      to: {photos_dst}')
print()
shutil.copytree(photos_src, photos_dst)

print('Getting best pictures')
print()
bestpix.main()