#!/bin/bash/python3

import os
import time
import shutil

from bestpix import PhotosInterface

os.system('clear')
time.sleep(1)

pi = PhotosInterface()
pi.find_photos()

command = f"docker run --rm -it -p 127.0.0.1:8442:8442 --volume {pi.temp_folder}:/opt/bestpix_data bluehalswater/bestpix"

print('Running command:')
print(f'    {command}')
print()
os.system(command)